CREATE TABLE IF NOT EXISTS ORDERITEM (
  id       IDENTITY,
  orderId  BIGINT,
  flowerId BIGINT,
  amount   INT,
  subTotal DECIMAL,
  FOREIGN KEY (orderId) REFERENCES "ORDER" (id) ON DELETE CASCADE,
  FOREIGN KEY (flowerId) REFERENCES FLOWER (id) ON DELETE RESTRICT
);